"""empty message

Revision ID: 2c49b6a586b3
Revises: d966e493b9b0
Create Date: 2022-06-23 17:37:38.875750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c49b6a586b3'
down_revision = 'd966e493b9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('uid', sa.String(length=50), nullable=True))
    op.drop_column('character', '_id')
    op.add_column('planet', sa.Column('uid', sa.String(length=50), nullable=True))
    op.drop_column('planet', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('planet', 'uid')
    op.add_column('character', sa.Column('_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('character', 'uid')
    # ### end Alembic commands ###
