"""empty message

Revision ID: c4ed51f5c1f5
Revises: c11965dc6fee
Create Date: 2022-06-21 13:27:26.849264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4ed51f5c1f5'
down_revision = 'c11965dc6fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
