"""empty message

Revision ID: d516a8494494
Revises: 2c49b6a586b3
Create Date: 2022-06-23 17:59:02.522670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd516a8494494'
down_revision = '2c49b6a586b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('year_of_birt', sa.String(length=250), nullable=True))
    op.drop_column('character', 'birth_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('birth_year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('character', 'year_of_birt')
    # ### end Alembic commands ###
