"""empty message

Revision ID: d966e493b9b0
Revises: f2193efccf2a
Create Date: 2022-06-21 17:59:49.267009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd966e493b9b0'
down_revision = 'f2193efccf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('_id', sa.String(length=50), nullable=True))
    op.add_column('planet', sa.Column('_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', '_id')
    op.drop_column('character', '_id')
    # ### end Alembic commands ###
